package com.example.jdkproject.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
@Getter
public enum ErrorStatus {
    NOT_FOUND(HttpStatus.NOT_FOUND, 101, "NOT FOUND"),
    ALREADY_EXIST(HttpStatus.BAD_REQUEST, 102, "ALREAY EXIST"),
    PARAMETER_NOT_FOUND(HttpStatus.BAD_REQUEST, 103, "PARAMETER NOT FOUND"),
    WRONG_USER_PASSWORD(HttpStatus.BAD_REQUEST, 105, "WRONG USER PASSWORD"),
    CANNOT_UPDATE_NICKNAME(HttpStatus.BAD_REQUEST, 106, "CANNOT UPDATE NICKNAME"),
    SAME_PASSWORD(HttpStatus.BAD_REQUEST, 107, "SAME PREV PASSWORD"),
    WRONG_REQUEST(HttpStatus.BAD_REQUEST, 108, "WRONG REQUEST"),

    NOT_REGISTERED_IDP(HttpStatus.BAD_REQUEST, 110, "NOT REGISTERED IDP"),

    TOKEN_VERIFY_FAIL(HttpStatus.BAD_REQUEST, 201, "TOKEN VERIFY FAIL"),
    TOKEN_PARSE_ERROR(HttpStatus.BAD_REQUEST, 202, "TOKEN PARSE FAIL"),
    REFRESH_TOKEN_VERIFY_FAIL(HttpStatus.BAD_REQUEST, 203, "REFRESH TOKEN VERIFY FAIL"),
    EXPIRED_TOKEN(HttpStatus.BAD_REQUEST, 204, "TOKEN EXPIRED"),
    EXCEEDED_EMAIL_TOKEN(HttpStatus.BAD_REQUEST, 205, "EMAIL TOKEN EXCEEDED"),
    EMAIL_TOKEN_VERIFY_FAIL(HttpStatus.BAD_REQUEST, 206, "EMAIL TOKEN VERIFY FAIL"),

    POSTING_REGISTER_FAIL(HttpStatus.BAD_REQUEST, 301, "POSTING REGISTER FAIL"),

    ALREADY_FOLLOW_MEMBER(HttpStatus.BAD_REQUEST, 310, "ALREADY FOLLOW MEMBER"),

    SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 501, "SERVER ERROR");

    private HttpStatus status;
    private int errorCode;
    private String message;
}
